{% set name = "implot" %}
{% set version = "0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/epezent/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 961df327d8a756304d1b0a67316eebdb1111d13d559f0d3415114ec0eb30abd1
  - path: CMakeLists.txt

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('implot', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
  host:
    - imgui
    - libvulkan-headers
    - libvulkan-loader
  run:
    - libvulkan-headers
    - libvulkan-loader

test:
  commands:
    - test -f $PREFIX/include/implot.h  # [not win]
    - test -f $PREFIX/lib/libimplot${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/share/implot/implot-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\implot.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\implot.lib  exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\implot.dll  exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\implot\\implot-config.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja  # [not win]
  files:
    - tests/

about:
  home: https://github.com/epezent/implot
  summary: Immediate Mode Plotting
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
